@echo off
echo ParkScore 개발 서버 재시작 중...
cd /d E:\ParkScore
echo .next 폴더 삭제 중...
if exist .next rmdir /s /q .next
echo node_modules 캐시 삭제 중...
if exist node_modules\.cache rmdir /s /q node_modules\.cache
echo 개발 서버 시작 중...
npm run dev
pause 